// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQHtLTQCPoQSAROQHKpFcDN-xuKkYlzg',
    appId: '1:809208530029:web:e823b1a85e167ec9cbab64',
    messagingSenderId: '809208530029',
    projectId: 'tallerii-4104d',
    authDomain: 'tallerii-4104d.firebaseapp.com',
    storageBucket: 'tallerii-4104d.appspot.com',
    measurementId: 'G-0E1TRG4GFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNaOxY1QCvMRB3Eosa1hEk7xSp-arip_M',
    appId: '1:809208530029:android:94a804a0a7cd4890cbab64',
    messagingSenderId: '809208530029',
    projectId: 'tallerii-4104d',
    storageBucket: 'tallerii-4104d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG23ReO1phlKczlTi8lZXuqzx_mFU-6BA',
    appId: '1:809208530029:ios:5146c9b029bbffd6cbab64',
    messagingSenderId: '809208530029',
    projectId: 'tallerii-4104d',
    storageBucket: 'tallerii-4104d.appspot.com',
    iosBundleId: 'com.ulagos.parking.uparking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG23ReO1phlKczlTi8lZXuqzx_mFU-6BA',
    appId: '1:809208530029:ios:fdb74ad64247a061cbab64',
    messagingSenderId: '809208530029',
    projectId: 'tallerii-4104d',
    storageBucket: 'tallerii-4104d.appspot.com',
    iosBundleId: 'com.ulagos.parking.uparking.RunnerTests',
  );
}
